server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    password: password
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.mail.ru
    port: 465
    username: zerone34@mail.ru
    password: UKeakYphbz3NrSvAkq9R
    test-connection: true
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
